# Generated by Django 2.2.17 on 2020-12-22 15:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dummygenerator', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakecsvschemacolumn',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='fakecsvschema',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fakecsvschema',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fakecsvschema',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fakecsvschemacolumn',
            name='data_range_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='fakecsvschemacolumn',
            name='data_range_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='fakecsvschemacolumn',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='column name'),
        ),
        migrations.CreateModel(
            name='ExportedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'processing'), (1, 'ready'), (2, 'error')], default=0)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('task_id', models.TextField()),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemadatasets', to='dummygenerator.FakeCSVSchema')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
