# Generated by Django 2.2.17 on 2020-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dummygenerator", "0002_auto_20201220_1421"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakecsvschemacolumn",
            name="name",
            field=models.TextField(blank=True, null=True, verbose_name="column name"),
        ),
    ]
