# Generated by Django 2.2.17 on 2020-12-20 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dummygenerator", "0004_auto_20201220_2109"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fakecsvschemacolumn", options={"ordering": ("order",)},
        ),
    ]
