# Generated by Django 2.2.17 on 2020-12-22 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummygenerator', '0005_auto_20201220_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakecsvschemacolumn',
            name='data_range_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='from'),
        ),
        migrations.AlterField(
            model_name='fakecsvschemacolumn',
            name='data_range_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='to'),
        ),
        migrations.CreateModel(
            name='ExportedDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'processing'), (1, 'ready'), (2, 'error')], default=0)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('task_id', models.TextField()),
                ('schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schemadatasets', to='dummygenerator.FakeCSVSchema')),
            ],
        ),
    ]
