# Generated by Django 2.2.17 on 2020-12-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummygenerator', '0006_auto_20201222_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exporteddataset',
            options={'ordering': ('-created',)},
        ),
    ]
